Update index.html
asxrow66/oreo-site pull request #1
Opened 2024-06-10 23:47 UTC by idksomerandomguy

what the balls

2024-06-11 00:00 UTC, asxrow66 requested changes

2024-06-11 00:00 UTC, asxrow66 commented on index.html
> +        <img src="file:///Users/rlo/Downloads/zazu%20madermelon.jpeg">alt="car">
alt isn't required, send me the photo, and add "height=""" and "width=""" to limit the height and width of the image and add the image you want to use in the pull request.

2024-06-11 01:39 UTC, idksomerandomguy commented on index.html
> +        <img src="file:///Users/rlo/Downloads/zazu%20madermelon.jpeg">alt="car">
uhhhhhh how do i do it
![Uploading zazu madermelon.jpeg…]()

2024-06-12 02:05 UTC, asxrow66 approved these changes

2024-06-12 02:05 UTC, merged